<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Login extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Customer_model');
    }

    public function index()
    {
		if($this->session->userdata('logined') && $this->session->userdata('logined') == true)
		{
			redirect('customer');
		}
		
		if(!$this->input->post())
		{
			$this->load->view('login');
		}
		else
		{
			$username = $this->input->post('username');
			$password = $this->input->post('password');
			if($username == 'admin' && $password == 'admin'){
				$this->session->set_userdata('logined', true);
				$this->session->set_userdata('username', 'admin');
				$this->session->set_userdata('status', 'admin');
				redirect("customer");
			}
			else{
				$cek_login=$this->Customer_model->cek_login(
					$this->input->post('username'),
					$this->input->post('password')
				);

				if(!empty($cek_login))
				{
				$this->session->set_userdata('logined', true);
				$this->session->set_userdata('username', $cek_login->username);
				$this->session->set_userdata('nama_customer', $cek_login->nama_customer);
				$this->session->set_userdata('status', 'customer');
				redirect("makanan");
			}
			else 
			{
				$this->session->set_flashdata('Gagal','<div class="alert alert-danger"><strong>Gagal login!</strong> Username dan Password Anda Salah.
					</div>');
				redirect("/");
			}
		}
        
    } }
	
	public function logout()
    {
		
		$this->session->unset_userdata('logined');
		$this->session->unset_userdata('username');
		$this->session->unset_userdata('nama_customer');
		$this->session->unset_userdata('status');
		session_destroy();
		redirect("/");
    } 
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */